Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,6 +17,8 @@ jobs:
   build:
 
     runs-on: ${{ matrix.os }}
+    permissions:
+      checks: writes
     strategy:
       matrix:
         os: [ubuntu-latest] 
@@ -35,3 +37,14 @@ jobs:
         pip install -r requirements.txt
     - name: Test with tox
       run: tox
+
+    - name: Test with pytest
+      run: |
+        python -m pytest --verbose --junit-xml=junit.xml
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
+        detailed_summary: true
+        include_passed: true
